### ISSUE TITLE
Compare retriv's permance to rank_bm25 and pyserini

### ISSUE THREAD

**Issue by MarshtompCS** [AmenRa/retriv#28]
Hi! I see that retriv's speed is really impressive in seepd.md. Did you also compare their performances?

**Comment by AmenRa** [comment]
The main problem with BM25 baselines is that most of the people do not optimize its hyper-parameters when performing comparisons. That's one of the main motivation `retriv` as a feature to allow you doing that very easily.

Regarding performances, as of now, `retriv` out-of-the-box performs as follows:
`MSMARCO Dev   MRR@10: 0.185 Recall: 0.873`
`TREC DL 2019 NDCG@10: 0.479 Recall: 0.753`
`TREC DL 2020 NDCG@10: 0.496 Recall: 0.811`

`Pyserini` out-of-the-box performs as follows:
`MSMARCO Dev   MRR@10: 0.184 Recall: 0.853`
`TREC DL 2019 NDCG@10: 0.506 Recall: 0.750`
`TREC DL 2020 NDCG@10: 0.480 Recall: 0.786`

The differences you see are mainly due to the the different default BM25's hyper-parameters setting of the two libraries and to a slightly different text pre-processing pipeline.

**Comment by MarshtompCS** [comment]
That's great! Thanks for repoting this!
